config/routes.rb
Rails.application.routes.draw do
  get'/home', to: 'home#home'
  get'/index', to: 'gossip#index'
  get 'static_pages/contact'
  get 'static_pages/team'
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
    resources :gossip do
      resources :comments
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, 
  presence: true,
  length: { in: 4..14 }
  validates :content,
  presence: true
  
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  validates :email, presence: true, uniqueness: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  
  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit

  end

  def create
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.create(comment_params)
    redirect_to gossip_path(@gossip)
  end

  def update

  end

  def destroy
    @gossip= Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.find(params[:id])
    @comment.destroy
    redirect_to gossip_path(@gossip)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter)
  end

end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  before_action :authenticate_user, only: [:index]

  def index
    @gossip = Gossip.all
  end

  def new
    @gossip = Gossip.new
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments =  Comment.where(gossip_id: params[:id])
  end

  def create
    @gossip = Gossip.create(gossip_params)
    @gossip.user = User.find_by(id: session[:user_id])
    if @gossip.save
      flash[:success] = "Potin bien créé !"
      redirect_to gossip_index_path
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
      @gossip = Gossip.find(params[:id])
      if @gossip.update(gossip_params)
        redirect_to gossip_index_path
        else
        redirect_to edit_gossip_path
        end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossip_index_path
  end

  private
  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end
  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user, only: [:index]

  def new
  end
  
  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id  
      redirect_to '/gossip'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to gossip_index_path, notice: "Logged out!"
  end



  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def team
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to gossip_index_path
  end

  def update

  end

  def destroy
    @user.destroy
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :bio, :email, :age, :city, :password)
  end

end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>pute</h1>

app/views/gossip/edit.html.erb
<h1 class="p-5">Edit gossip</h1>

<%= form_for @gossip do |f|%>
   <div class="form-group">
    <label>Titre de l'article</label>
    <%= f.text_field :title, class: 'form-control' %><br />
  </div>

  <div class="form-group">
    <label>Contenu de l'article</label>
    <%= f.text_field :content, class: 'form-control'  %><br />
  <div>  

  <div class="form-group">
    <%= f.submit %> 
  <div>
<% end %>

app/views/gossip/index.html.erb
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

<title>Cover Template for Bootstrap</title>

<link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/cover/">

<!-- Bootstrap core CSS -->
<link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="cover.css" rel="stylesheet">
</head>


<body class="text-center">
<h1 style="text-align: center; padding-top: 140px;">Bienvenue sur the Hacking Gossip !</h1>
<br>
<a href= "<%= new_gossip_path %>" class = "btn btn-light btn-outline-info center;"> Créer un nouveau gossip</a>
<br>
<p style="margin-left: 10px; center;">Voici la liste des différents gossips...</p>
<br>

<% @gossip.each do |gossip| %>
  <div class="card-deck">
    <div class="card">
  <div class="card text-center">
  <div class="card-header text-white bg-secondary">
    The Story
  </div>
  <div class="card-body border-danger text-white bg-dark mb-3">
    <h5 class="card-title border-danger text-white bg-dark"><%=  gossip.title %></h5>
    <p class="card-text border-danger text-white bg-dark"><%=  gossip.content %></p>
    <a href= "<%= edit_gossip_path(gossip.id) %>" class = "btn btn-light"> Edit</a>
    <a href= "<%= gossip_path(gossip.id) %>" class = "btn btn-light"> See Gossip </a>

</div>
</div>

<% end %>

  </main>

</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>


</body></html>

app/views/gossip/new.html.erb
<html>
  <head>
    <title class="p-5">Créer un potin</title>
  </head>
  <body>
    <h1>Crée un potin !</h1>
    <p>Balance ton potin via le formulaire ci-dessous</p>
    
    <%= form_for :gossip, url: gossip_index_path  do |f| %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <div class="form-group">
    <label>Titre de l'article</label>
    <%= f.text_field :title, class: 'form-control' %><br />
  </div>

  <div class="form-group">
    <label>Contenu de l'article</label>
    <%= f.text_field :content, class: 'form-control'  %><br />
  <div>  

  <div class="form-group">
    <%= f.submit %> 
  <div>  
  
  
  
<% end %>
  </body>
</html>

app/views/gossip/show.html.erb
<h1 class="p-5">Le show</h1>

<div>
<p>Titre : <%= @gossip.title %></p>
<p>Contenu : <%= @gossip.content %></p>
</div>

<a href ="<%= edit_gossip_path%>" class = "btn btn-primary">Editer l'article</a>      
<a href ="<%= gossip_path %>" class = "btn btn-danger" data-method = "DELETE">Supprimer l'article</a>
<a href="<%= gossip_index_path%>"class = "btn btn-success">Revenir au menu<a>


<%= form_with(model: [ @gossip, @gossip.comments.build ], local: true) do |f| %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <div class="form-group">
    <label>Ton commentaire</label>
    <%= f.text_area :commenter, class: 'form-control' %><br />
  </div>
  
  <div class="form-group">
    <%= f.submit %> 
  <div>  
  
  <% end %>

   
<% @gossip.comments.each do |comment| %>
  <p>
    <strong>Commentaire:</strong>
    <%= comment.commenter %>
  </p>
  <% end %>

  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="fixed-top navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
      <a class="navbar-brand text-while" href="#"><img id="logo" src="https://cdn.pixabay.com/photo/2018/09/02/22/06/secret-3650080_1280.png"
              class="d-inline-block align-bottom mr-0.5" width="35" height="35" href="/home" alt="">
          The Gossip Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                  <a class="nav-link text-white" href="/index">Index</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-white" href="/static_pages/team">Team</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-white" href="/static_pages/contact">Contact</a>
              </li>
              <li>
              <% if current_user %>
              Logged in as <%= current_user.email %>.
              <%= link_to "Log Out", logout_path %>
            <% else %>
              <%= link_to "Sign Up", signup_path %>
              <%= link_to "Log In", login_path %>
            <% end %>
            <p id=”notice”><%= notice %></p>
              </div>
              </li>
          </ul>
  </div>
</nav>

    <%= yield %>
  </body>
</html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<p id=”alert”><%= alert %></p>
<h1>Login</h1>
<%= form_tag sessions_path do |form| %>
  <div class=”field”>
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </div>
  <div class=”field”>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class=”actions”>
    <%= submit_tag “Login” %>
  </div>
<% end %>

<p id=”alert”><%= alert %></p>
<h1>Login</h1>

app/views/static_pages/contact.html.erb
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Cover Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/cover/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>


  <body class="text-center">

      <main role="main" class="inner cover">
        <h1 class="cover-heading" style="text-align: center; padding-top: 140px;">Contact Page.</h1>
        <br>
        <h4 class="lead">Find US on Twitter Motherfucker</h4>
        <br>
        <h5 class="lead">At@NotExistingPagesLOL !</h5>
        <br>
        <a href="<%= gossip_index_path%>"class = "btn btn-success">Back<a>
        </p>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Made In France</p>
        </div>
      </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  

</body></html>

app/views/static_pages/team.html.erb
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Cover Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/cover/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>


  <body class="text-center">

      <main role="main" class="inner cover">
        <h1 class="cover-heading" style="text-align: center; padding-top: 140px;">Our Creators.</h1>
        <br>
        <h4 class="lead">Designed by an astonishing team of Gossipers</h4>
        <br>
        <p class="lead">Basil Balladhère</p>
        <p class="lead">Théo Fierdtoa</p>
        <p class="lead">Youfesse Annabi</p>
        <p class="lead">Alexandre Gauthier</p>
        <p class="lead">Mehdi EA Sport</p>
        <p class="lead">Monique Ranou</p>
        <p class="lead">
        <a href="<%= gossip_index_path%>"class = "btn btn-success">Back<a>
        </p>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Made In France</p>
        </div>
      </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  

</body></html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Bio</th>
      <th>Age</th>
      <th>City</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.bio %></td>
        <td><%= user.age %></td>
        <td><%= user.city %></td>
        <td><%= user.bio %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="titi p-5">New User</h1>

<%= render 'form', user: @user %>



<%= link_to 'Back', gossip_index_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>